/******************************************************************************/
/*                 Generated by IBExpert 23/11/2022 16:35:33                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR GEN_TB_CLIENTES_ID;

CREATE TABLE TB_CLIENTES (
    ID_CLIENTE       INTEGER NOT NULL,
    STR_NOME         VARCHAR(100) NOT NULL,
    STR_CPF          VARCHAR(14) NOT NULL,
    STR_TELEFONE     VARCHAR(20),
    DT_NASCIMENTO    DATE,
    DT_CADASTRO      DATE,
    DT_ALTERADO      DATE,
    STR_ENDERECO     VARCHAR(100),
    STR_NUM          VARCHAR(10),
    STR_COMPLEMENTO  VARCHAR(25),
    STR_CEP	     VARCHAR(11),
    STR_BAIRRO       VARCHAR(45),
    STR_CIDADE       VARCHAR(45),
    STR_UF           CHAR(2),
    STR_OBS          VARCHAR(255)
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE TB_CLIENTES ADD PRIMARY KEY (ID_CLIENTE);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: TB_CLIENTES_BI */
CREATE OR ALTER TRIGGER TB_CLIENTES_BI FOR TB_CLIENTES
ACTIVE BEFORE INSERT POSITION 1
as
begin
  if (new.id_cliente is null) then
    new.id_cliente = gen_id(gen_tb_clientes_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/


/******************************************************************************/
/*                 Generated by IBExpert 23/11/2022 16:30:20                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR GEN_TB_OPERACAO_FINANCEIRA_ID;

CREATE TABLE TB_OPERACAO_FINANCEIRA (
    ID_OPERACAO          INTEGER NOT NULL,
    CLI_ID_CLIENTE       INTEGER NOT NULL,
    STR_TIPO_OPERACAO    VARCHAR(45) NOT NULL,
    STR_NUM_DOC		 VARCHAR(45),
    STR_DESCRICAO        VARCHAR(100),
    DT_OPERACAO          DATE,
    DT_ALTERADO		 DATE,
    DT_CADASTRO          DATE,
    FL_VALOR             decimal(14,2),
    FL_SALDO             decimal(14,2),
    STR_OBS              VARCHAR(255)
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE TB_OPERACAO_FINANCEIRA ADD PRIMARY KEY (ID_OPERACAO);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE TB_OPERACAO_FINANCEIRA ADD CONSTRAINT FK_TB_OPERACAO_FINANCEIRA_1 FOREIGN KEY (CLI_ID_CLIENTE) REFERENCES TB_CLIENTES (ID_CLIENTE);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: TB_OPERACAO_FINANCEIRA_BI */
CREATE OR ALTER TRIGGER TB_OPERACAO_FINANCEIRA_BI FOR TB_OPERACAO_FINANCEIRA
ACTIVE BEFORE INSERT POSITION 1
as
begin
  if (new.id_operacao is null) then
    new.id_operacao = gen_id(gen_tb_operacao_financeira_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
